# Generated by Django 5.2.6 on 2026-02-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='machine_id',
        ),
    ]
