# Generated by Django 5.2.6 on 2026-02-23 03:29

from django.db import migrations, models


def attribuer_numeros(apps, schema_editor):
    Reservation = apps.get_model('laverie', 'Reservation')
    for i, resa in enumerate(Reservation.objects.order_by('pk'), start=1):
        resa.numero = i
        resa.save(update_fields=['numero'])


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='numero',
            field=models.PositiveIntegerField(blank=True, help_text="Numéro de ticket (séquentiel, affiché à l'utilisateur)", null=True, unique=True),
        ),
        migrations.RunPython(attribuer_numeros, migrations.RunPython.noop),
    ]
