# Generated by Django 5.2.6 on 2026-02-23 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0002_add_reservation_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLaverie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(help_text='Message affiché aux utilisateurs', max_length=500)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)")),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_laverie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message laverie',
                'verbose_name_plural': 'Messages laverie',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
    ]
