# Generated by Django 5.2.6 on 2026-02-23 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0003_add_message_laverie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementLaverie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Explication du problème par l'étudiant")),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, help_text='Machine concernée si le problème en concerne une', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='laverie.machine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_laverie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement laverie',
                'verbose_name_plural': 'Signalements laverie',
                'ordering': ['-date_creation'],
            },
        ),
    ]
