# Generated by Django 5.2.6 on 2026-02-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0004_add_signalement_laverie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignalementLaverie',
        ),
    ]
