# Generated by Django 5.2.6 on 2026-03-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0005_remove_signalement_laverie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('reserve', 'Reserved'), ('en_cours', 'In progress'), ('termine', 'Completed'), ('annule', 'Cancelled')], default='reserve', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatMachineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=1000)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_laverie', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='laverie.machine')),
            ],
            options={
                'verbose_name': 'Machine chat message',
                'verbose_name_plural': 'Machine chat messages',
                'ordering': ['date_creation'],
            },
        ),
    ]
